eHealth/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('administrador.urls')),
    url(r'^medico/', include('medico.urls')),
    url(r'^paciente/', include('paciente.urls')),
    url(r'^farmaceuta/', include('farmaceuta.urls')),
    ]

farmaceuta/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve
from farmaceuta.views import *


urlpatterns = [
    url(
        r'^agregar-farmacia$',
        agregarFarmacia.as_view(),
        name='agregar_farmacia'
    ),
    url(
        r'^ver-farmacias$',
        verFarmacias.as_view(),
        name='ver_farmacias'
    ),
    url(
        r'^modificar-farmacia/(?P<pk>\w+)$',
        ModificarFarmacia.as_view(),
        name='modificar_farmacia'
    ),
    url(
        r'^eliminar-farmacia/(?P<pk>\w+)$',
        'farmaceuta.controllers.eliminar_farmacia',
        name='eliminar_farmacia'
    ),
    url(
        r'^perfil-farmaceuta/(?P<id>\w+)$',
        PerfilFarmaceuta.as_view(),
        name='perfil_farmaceuta'
    ),
    
    url(
        r'^ver-farmacias-farmaceuta/(?P<pk>\w+)$',
        VerFarmaciasFarmaceuta.as_view(),
        name='ver_farmacias_farmaceuta'
    ),

    url(
        r'^ver-medicamentos/(?P<pk>\w+)$',
        VerMedicamentos.as_view(),
        name='ver_medicamentos'
    ),

    url(
        r'^agregar-medicamentos/(?P<pk>\w+)$',
        AgregarMedicamentos.as_view(),
        name='agregar_medicamentos'
    ),

    url(
        r'^eliminar-medicamentos/(?P<pk>\w+)/(?P<farmacia>\w+)$',
        'farmaceuta.controllers.eliminar_medicamento',
        name='eliminar_medicamentos'
    ),

    url(
        r'^modificar-medicamento/(?P<pk>\w+)/(?P<farmacia>\w+)$',
        ModificarMedicamento.as_view(),
        name='modificar_medicamento'
    ),
    url(
        r'^agregar-lote/(?P<pk>\w+)/(?P<farmacia>\w+)$',
        AgregarLoteMedicamento.as_view(),
        name='agregar_lote'
    ),

]

medico/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve
from medico.views import *
from farmaceuta.controllers import *


urlpatterns = [
    url(
        r'^perfil-medico/(?P<id>\w+)$',
        PerfilMedico.as_view(),
        name='perfil_medico'
    ),
    url(
        r'^agregar-estudios/(?P<id>\w+)$',
        AgregarEstudios.as_view(),
        name='agregar_estudios'
    ),
    url(
        r'^eliminar-recipe/(?P<pk>\w+)$',
        'farmaceuta.controllers.eliminar_recipe',
        name='eliminar_recipe'
    ),
    url(
        r'^modificar-estudios/(?P<id>\w+)$',
        ModificarEstudios.as_view(),
        name='modificar_estudios'
    ),
    url(
        r'^eliminar-estudios/(?P<id>\w+)$',
        'medico.controllers.eliminar_estudios',
        name='eliminar_estudios'
    ),
    url(
        r'^agregar-reconocimientos/(?P<id>\w+)$',
        AgregarReconocimientos.as_view(),
        name='agregar_reconocimientos'
    ),
    url(
        r'^modificar-reconocimientos/(?P<id>\w+)$',
        ModificarReconocimientos.as_view(),
        name='modificar_reconocimientos'
    ),
    url(
        r'^eliminar-reconocimientos/(?P<id>\w+)$',
        'medico.controllers.eliminar_reconocimientos',
        name='eliminar_reconocimientos'
    ),
    url(
        r'^agregar-publicaciones/(?P<id>\w+)$',
        AgregarPublicaciones.as_view(),
        name='agregar_publicaciones'
    ),
    url(
        r'^modificar-publicaciones/(?P<id>\w+)$',
        ModificarPublicaciones.as_view(),
        name='modificar_publicaciones'
    ),
    url(
        r'^eliminar-publicaciones/(?P<id>\w+)$',
        'medico.controllers.eliminar_publicaciones',
        name='eliminar_publicaciones'
    ),
    url(
        r'^agregar-experiencias/(?P<id>\w+)$',
        AgregarExperiencias.as_view(),
        name='agregar_experiencias'
    ),
    url(
        r'^modificar-experiencias/(?P<id>\w+)$',
        ModificarExperiencias.as_view(),
        name='modificar_experiencias'
    ),
    url(
        r'^eliminar-experiencias/(?P<id>\w+)$',
        'medico.controllers.eliminar_experiencias',
        name='eliminar_experiencias'
    ),
    url(
        r'^agregar-habilidades/(?P<id>\w+)$',
        AgregarHabilidades.as_view(),
        name='agregar_habilidades'
    ),
    url(
        r'^modificar-habilidades/(?P<id>\w+)$',
        ModificarHabilidades.as_view(),
        name='modificar_habilidades'
    ),
    url(
        r'^eliminar-habilidades/(?P<id>\w+)$',
        'medico.controllers.eliminar_habilidades',
        name='eliminar_habilidades'
    ),
    url(
        r'^agregar-eventos/(?P<id>\w+)$',
        AgregarEventos.as_view(),
        name='agregar_eventos'
    ),
    url(
        r'^modificar-eventos/(?P<id>\w+)$',
        ModificarEventos.as_view(),
        name='modificar_eventos'
    ),
    url(
        r'^eliminar-eventos/(?P<id>\w+)$',
        'medico.controllers.eliminar_eventos',
        name='eliminar_eventos'
    ),
    url(
        r'^ver-consultas/(?P<id>\w+)$',
        VerConsultas.as_view(),
        name='ver_consultas'
    ),
    url(
        r'^agregar-consulta/(?P<id>\w+)$',
        AgregarConsulta.as_view(),
        name='agregar_consulta'
    ),
    url(
        r'^modificar-consulta/(?P<user>\w+)/(?P<id>\w+)$',
        ModificarConsultas.as_view(),
        name='modificar_consulta'
    ),
    url(
        r'^eliminar-consulta/(?P<id>\w+)$',
        'medico.controllers.eliminar_consultas',
        name='eliminar_consulta'
    ),
    url(
        r'^buscar-paciente$',
        BuscarPaciente.as_view(),
        name='buscar_paciente'
    ),
    url(
        r'^buscar-medico$',
        BuscarMedico.as_view(),
        name='buscar_medico'
    ),
    url(
        r'^ver-citas/(?P<id>\w+)$',
        VerCitas.as_view(),
        name='ver_citas'
    ),
    url(
        r'^agregar-cita/(?P<id>\w+)$',
        AgregarCitas.as_view(),
        name='agregar_cita'
    ),
    url(
        r'^modificar-cita/(?P<id>\w+)$',
        ModificarCitas.as_view(),
        name='modificar_cita'
    ),
    url(
        r'^eliminar-cita/(?P<id>\w+)$',
        'medico.controllers.eliminar_citas',
        name='eliminar_cita'
    ),
    url(
        r'^historias/$',
        HistoriasClinicas.as_view(),
        name='historias_clinicas'
    ),
    url(
        r'^historias/new/$',
        HistoriasClinicasCrear.as_view(),
        name='crear_historias_clinicas'
    ),
    url(
        r'^ver-historia-clinica/(?P<pk>\w+)$',
        HistoriasClinicasModificar.as_view(),
        name='ver_historia_clinica'
    ),
    url(
        r'^eliminar-historia_clinica/(?P<id>\w+)$',
        'medico.controllers.eliminar_historia_clinica',
        name='eliminar_historia_clinica'
    ),
    url(
        r'^consulta/(?P<id>\w+)$',
        Consultas.as_view(),
        name='consulta'
    ),
    url(
        r'^comenzar-revision/(?P<id>\w+)$',
        ComenzarRevision.as_view(),
        name='comenzar_revision'
    ),
    url(
        r'^informe-medico/(?P<id>\w+)$',
        InformeMedico.as_view(),
        name='informe_medico'
    ),

    url(
        r'^pdf-informe/(?P<id>\w+)$',
        MyPDFView.as_view(),
        name='generarPDF'
    ),
    url(
        r'^referir-paciente/(?P<id>\w+)$',
        ReferirPaciente.as_view(),
        name='referir_paciente'
    ),
    url(
        r'^ver-historial/(?P<id>\w+)$',
        VerHistorial.as_view(),
        name='ver_historial'
    ),
    url(
        r'^ver-recipes/',
        VerRecipes.as_view(),
        name='ver_recipes'
    ),
    url(
        r'^agregar-recipe/',
        AgregarRecipe.as_view(),
        name='agregar_recipe'
    ),
    url(
        r'^modificar-recipe/(?P<pk>\w+)$',
        ModificarRecipe.as_view(),
        name='modificar_recipe'
    ),

]

farmaceuta/models.py
from django.db import models
from django.db.models import Q
from administrador.models import *
from medico.models import *
from django.core.validators import MaxValueValidator

# Create your models here.
class Farmaceuta(models.Model):
    cedula = models.IntegerField(primary_key=True,
                                 validators=[MaxValueValidator(99999999)])
    first_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=30, blank=True, null=True)
    fecha_nacimiento = models.DateField(null=True)
    sexo = models.CharField(max_length=10, blank=True, null=True)
    estado_civil = models.CharField(max_length=15, blank=True, null=True)
    telefono = models.CharField(max_length=15, blank=True, null=True)
    direccion = models.CharField(max_length=100, blank=True, null=True)
    usuario = models.ForeignKey(Usuario,
                                on_delete=models.CASCADE)

    def __str__(self):
        return str(self.cedula) + " " + self.first_name + " " + self.last_name


class Farmacia(models.Model):
    
    rif = models.CharField(max_length=12, blank=False)
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=255, blank=False)
    institucion = models.ForeignKey(Institucion,
    								limit_choices_to=Q(tipo='Clinica') | Q(tipo='Hospital'),
    								null=True,
    								blank=True)
    farmaceuta = models.ForeignKey(Farmaceuta, null=True, blank=True)

    def __str__(self):
        return self.nombre


class Medicamento(models.Model):
    nombre = models.CharField(max_length=256, blank=False)
    indicacion = models.TextField(max_length=512, blank=False)
    posologia = models.TextField(max_length=512, blank=False)
    marca = models.ForeignKey(Institucion, limit_choices_to=Q(tipo='Laboratorio'))
    # stock = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(99999999)])
    tipo = models.CharField(max_length=32, choices={('grajeas', 'Grajeas'),
                                                    ('jarabe', 'Jarabe'),
                                                    ('inyectable', 'Inyectable')})
    # farmacia = models.ForeignKey(Farmacia)


    def __str__(self):
        return self.nombre 


class Inventario(models.Model):
    farmacia = models.ForeignKey(Farmacia, null=True)
    medicamento = models.ForeignKey(Medicamento, null=True)
    cantidad = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(99999999)])


class Lote(models.Model):
    # medicamento = models.ForeignKey(Medicamento)
    inventario = models.ForeignKey(Inventario, null=True)
    f_elaboracion = models.DateField()
    f_vencimiento = models.DateField()
    precio = models.DecimalField(max_digits=15, decimal_places=2)
    cantidad = models.PositiveIntegerField()
    activo = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.inventario.cantidad += self.cantidad
        self.inventario.save()
        super(Lote, self).save(*args, **kwargs)

    def __str__(self):
        return "Lote de: " + str(self.medicamento)

farmaceuta/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User, Group
from medico.models import *
from administrador.models import Usuario
from farmaceuta.models import *
import datetime



class farmacia_form(forms.ModelForm):
    class Meta:
        model = Farmacia
        fields = ['nombre','direccion', 'rif','institucion','farmaceuta']


	def __init__(self, *args, **kwargs):
		super(farmacia_form, self).__init__(*args, **kwargs)
		self.fields['institucion'].required = False


class FarmaciaFormEditar(forms.ModelForm):

    class Meta:
        model = Farmacia
        exclude = ["rif","nombre"]


    def __init__(self, *args, **kwargs):
    	super(FarmaciaFormEditar, self).__init__(*args, **kwargs)
    	self.fields['institucion'].empty_label = None

    # def clean_farmaceuta():


class MedicamentoForm(forms.ModelForm):
    class Meta:
        model = Medicamento
        fields = ['nombre', 'indicacion', 'posologia', 'tipo', 'marca']


    def __init__(self, *args, **kwargs):
        super(MedicamentoForm, self).__init__(*args, **kwargs)


class LoteForm(forms.ModelForm):
    class Meta:
        model = Lote
        exclude = ["activo", "inventario"]


    def __init__(self, *args, **kwargs):
        super(LoteForm, self).__init__(*args, **kwargs)
        self.fields['f_elaboracion'].widget.attrs['class'] = 'datepicker'
        self.fields['f_vencimiento'].widget.attrs['class'] = 'datepicker'
        # self.fields['medicamento'] = forms.ModelChoiceField(
        #     queryset=Medicamento.objects.filter(farmacia=self.kwargs['farmacia'])
        #     )

farmaceuta/controllers.py
from administrador.models import *
from farmaceuta.models import *
from medico.models import *
from medico.urls import *
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
import datetime
import parsedatetime as pdt


def editar_farmaceuta(user, nombre, apellido, email, sexo, fecha, estado_civil,
                      telefono, direccion, foto):
    try:
        usuario = Usuario.objects.get(user=user)
        user = User.objects.get(pk=usuario.user.pk)
        farmaceuta = Farmaceuta.objects.get(usuario=usuario)
        farmaceuta.first_name = nombre
        user.first_name = nombre
        farmaceuta.last_name = apellido
        user.last_name = apellido
        farmaceuta.email = email
        user.email = email
        farmaceuta.sexo = sexo
        try:
            fecha = datetime.datetime.strptime(fecha,
                                               '%d-%m-%Y'
                                               ).strftime('%Y-%m-%d')
        except:
            if fecha is None:
                fecha = None
            else:
                cal = pdt.Calendar()
                now = datetime.datetime.now()
                fecha = cal.parseDT(fecha, now)[0]

        farmaceuta.fecha_nacimiento = fecha
        farmaceuta.estado_civil = estado_civil
        farmaceuta.telefono = telefono
        farmaceuta.direccion = direccion
        print("fotooooooooooooooo")
        print(foto == False)
        if foto != False :
            usuario.foto=foto
            usuario.fotosubida = True
        usuario.save()
        farmaceuta.save()
        user.save()
        return True

    except:
        return False


def modificar_farmacia(inst_id, direccion, institucion, farmaceuta):
    try:
        farmacia = Farmacia.objects.get(pk=int(inst_id))
        farmacia.direccion = direccion
        if institucion:
            institucion = Institucion.objects.get(id=institucion)
            farmacia.institucion = institucion
        if farmaceuta:
            farmaceuta = Farmaceuta.objects.get(cedula=farmaceuta)
            farmacia.farmaceuta = farmaceuta
        farmacia.save()
        return True
    except:
        return False


def eliminar_farmacia(request, pk):
    farmacia = Farmacia.objects.get(pk=pk)
    farmacia.delete()
    return HttpResponseRedirect(reverse_lazy(
        'ver_farmacias'))

def eliminar_medicamento(request, pk, farmacia):
    medicamento = Medicamento.objects.get(pk=pk)
    medicamento.delete()
    return HttpResponseRedirect(reverse_lazy('ver_medicamentos', kwargs={'pk': pk}))

def eliminar_recipe(request, pk):
    recipe = RecipeMedico.objects.get(pk=pk)
    recipe.delete()
    return HttpResponseRedirect(reverse_lazy(
        'ver_recipes'))
    return HttpResponseRedirect(reverse_lazy('ver_medicamentos', kwargs={'pk': farmacia}))

eHealth/templates/farmaceuta/agregar_lote.html
{% extends "base.html" %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1%}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% load static %}
{% block content %}
  <div id="cuerpoHeredado">
    <br>
    <h2>{{title}} Lote de {{medicamento.nombre}}</h2>
    {% if title == "Agregar" %}
    <form action="" method=POST>
    {% else %}
    <form action="" method=POST>
    {% endif %}
    {% csrf_token %}
    
    <div class="hidden">
        {% bootstrap_form_errors form %}
    </div>

    {% if messages %}
    <ul class="messages">
      {% for mes in messages %}
      <li{% if mes.tags  %}
      class="{{ mes.tag }}"
      {% endif%}>{{ mes }}
      </li>
      {% endfor %}
    </ul>
    {% endif %}

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <label for="id_f_elaboracion">Fecha de elaboración</label>
    {% bootstrap_field form.f_elaboracion layout="inline" %}
    <label for="id_f_vencimiento">Fecha de vencimiento</label>
    {% bootstrap_field form.f_vencimiento layout="inline" %}
    <label for="id_precio">Precio</label>
    {% bootstrap_field form.precio layout="inline" %}
    <label for="id_cantidad">Cantidad</label>
    {% bootstrap_field form.cantidad layout="inline" %}
        {% buttons %}
        <div class="col-md-3"></div>
        <div class="col-sm-4 col-md-6 text-center">
            <br>
            <button id="id_submit" type="submit" class="btn btn-lg calculate" >
                Guardar
            </button>
            <br>
            <br>
        </div>
        <div class="col-md-3"></div>
    {% endbuttons %}
    </form>
  </div>
{% endblock %}
{% block custom_script %}
<script type="text/javascript" src="{% static 'assets/js/bootstrap-datepicker.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/bootstrap-datepicker.es.min.js' %}"></script>

<!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script> -->
<!-- <script src="{% static 'plugins/datepicker/locales/bootstrap-datepicker.es.js' %}"></script> -->
<script type="text/javascript">
$(document).ready(function(){
  $( ".datepicker" ).datepicker({ format: 'dd-mm-yyyy' });
});
</script>
{% endblock %}

eHealth/templates/farmaceuta/agregar_medicamentos.html
{% extends "base.html" %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1%}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% load static %}
{% block content %}
  <div id="cuerpoHeredado">
    <br>
    <h2>{{title}} Medicamento</h2>
    {% if title == "Agregar" %}
    <form action="" method=POST>
    {% else %}
    <form action="" method=POST>
    {% endif %}
    {% csrf_token %}
    
    <div class="hidden">
        {% bootstrap_form_errors form %}
    </div>

    {% if messages %}
    <ul class="messages">
      {% for mes in messages %}
      <li{% if mes.tags  %}
      class="{{ mes.tag }}"
      {% endif%}>{{ mes }}
      </li>
      {% endfor %}
    </ul>
    {% endif %}

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <label for="id_nombre">Nombre</label>
    {% bootstrap_field form.nombre layout="inline" %}
    <label for="id_indicacion">Indicaciones</label>
    {% bootstrap_field form.indicacion layout="inline" %}
    <label for="id_posologia">Posología</label>
    {% bootstrap_field form.posologia layout="inline" %}
    <label for="id_tipo">Tipo</label>
    {% bootstrap_field form.tipo layout="inline" %}
    <label for="id_tipo">Marca</label>
    {% bootstrap_field form.marca layout="inline" %}
        {% buttons %}
        <div class="col-md-3"></div>
        <div class="col-sm-4 col-md-6 text-center">
            <br>
            <button id="id_submit" type="submit" class="btn btn-lg calculate" >
                Guardar
            </button>
            <br>
            <br>
        </div>
        <div class="col-md-3"></div>
    {% endbuttons %}
    </form>
  </div>
{% endblock %}

eHealth/templates/farmaceuta/ver_medicamentos.html
{% extends "base.html" %}
{% block content %}
  <div id="cuerpoHeredado">

    <center><h1>Gestión de Medicamentos de {{farmacia}}</h1></center>
    <div id="show-instituciones"><table id="search_result" class="display" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th style="text-align: center;">Nombre</th>
          <th style="text-align: center;">Tipo</th>
          <th style="text-align: center;">Laboratorio</th>
          <th style="text-align: center;">Inventario</th>
          <th style="text-align: center">
          <a id="add_institucion" href="{% url 'agregar_medicamentos' farmacia.pk %}">
            <i class="fa fa-plus-circle" style="font-size:20px;color:white"></i>
          </a>
          </th>
        </tr>
      </thead>
      <tbody>
      {% for medicamento in medicamentos %}
      <!-- Modal content -->
        <div class="modal fade" id="myModal{{medicamento.0.pk}}" role="dialog">
          <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Eliminar Medicamento</h4>
              </div>
              <div class="modal-body">
                <p>¿Está seguro que desea eliminar este medicamento?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <a type="button" class="btn btn-primary" href="{% url 'eliminar_medicamentos' medicamento.0.pk farmacia.pk %}" > Aceptar</a>
              </div>
            </div>
          </div>
        </div>
      
        <tr>
          <td style="text-align: center;">{{medicamento.0.nombre}}</td>
          <td style="text-align: center;">{{medicamento.0.tipo}}</td>
          <td style="text-align: center;">{{medicamento.0.marca}}</td>
          <td style="text-align: center;">
            {% if medicamento.1.cantidad %}
            {{medicamento.1.cantidad}}
            {% else %}
            0
            {% endif %}
            &nbsp;&nbsp; <a href="{% url 'agregar_lote' medicamento.0.pk farmacia.pk %}" title="Agregar inventario">
              <i class="fa fa-plus" style="font-size:14px;color:#5882FA"></i>
            </a>
          </td>

          <td style="text-align: center;">
            <a href="{% url 'modificar_medicamento' medicamento.0.pk farmacia.pk %}"><i class="fa fa-pencil" style="font-size:20px;color:#5882FA"></i></a>
            <a data-toggle="modal" data-target="#myModal{{medicamento.0.pk}}" ><i class="fa fa-trash" style="font-size:20px;color:#5882FA"></i></a>
          </td>
        </tr>
      {% endfor%}
      </tbody>
    </table></div>
  </div>
{% endblock %}